---
- name: Create CRI-O Machine Config
  include_tasks: create-crio-config.yml
  when: _mco_exists

- name: Apply CRI-O configuration if the Machine Config Operator does not exist
  include_tasks: non-mco-apply-crio-config.yml
  when: not _mco_exists