---
- name: Get first compute node
  shell: |
    oc get no --no-headers -l node-role.kubernetes.io/worker -o custom-columns='name:.metadata.name' | head -1
  register: _ocp_compute_nodes

- name: Retrieve /etc/crio/crio.conf
  shell: |
    {{ lookup('template','oc-debug-crio.j2') }}
  register: debug_node_result
  retries: 3
  delay: 10
  until: debug_node_result.rc==0

- name: Set pids_limit
  community.general.ini_file:
    path: "{{ status_dir }}/openshift/cp4d-crio.conf"
    section: "crio.runtime"
    option: pids_limit
    value: "12288"
    
- name: Add cp4d-crio.conf to node fix config map
  shell:
    oc set data -n kube-system cm/cloud-pak-node-fix-config  \
        --from-file={{ status_dir }}/openshift/cp4d-crio.conf