---
- name: Validate mandatory variables are defined
  assert:
    that:
      - ibmcloud_api_key is defined
      
- name: Show OpenShift cluster that is being processed
  debug:
    msg: "Handling OpenShift cluster {{ current_openshift_cluster.name }}"

- name: Login to the OpenShift cluster {{ current_openshift_cluster.name }}
  include_role:
    name: openshift-login
  vars:
    _p_openshift_cluster_name: "{{ current_openshift_cluster.name }}"

- name: Set OpenShift console banner if specified
  include_role:
    name: openshift-console-banner
  vars:
    _p_openshift_cluster: "{{ current_openshift_cluster }}"

- name: Specify or detect cloud infra for existing-ocp 
  include_role:
    name: retrieve-cloud-infra-type
  vars:
    _p_openshift_cluster: "{{ current_openshift_cluster }}"

- name: OpenShift Advanced Data Protection operator
  include_role:
    name: openshift-adp
  vars:
    _p_openshift_cluster: "{{ current_openshift_cluster }}"

- name: OpenShift NACL Security
  include_role:
    name: openshift-nacl-security
  vars:
    _p_openshift_cluster: "{{ current_openshift_cluster }}"

- name: Configure Cloud Native Toolkit OpenShift cluster {{ current_openshift_cluster.name }}
  include_role:
    name: cloud-native-toolkit
  vars:
    _p_openshift_cluster: "{{ current_openshift_cluster }}"

- name: Configure upstream DNS for OpenShift cluster {{ current_openshift_cluster.name }}
  include_role:
    name: configure-openshift-dns
  vars:
    _p_upstream_dns: "{{ current_openshift_cluster.upstream_dns | default([]) }}"

- name: Configure logging for OpenShift cluster {{ current_openshift_cluster.name }}
  include_role:
    name: openshift-logging

- name: Configure monitoring for OpenShift cluster {{ current_openshift_cluster.name }}
  include_role:
    name: openshift-monitoring

- name: Prepare storage for OpenShift cluster {{ current_openshift_cluster.name }}
  include_role:
    name: prepare-openshift-storage
  loop: "{{ current_openshift_cluster.openshift_storage | default([]) }}"
  loop_control:
    loop_var: current_openshift_storage
