---
- include_tasks: "{{ role_path }}/tasks/cp4d-install-cr-{{ _current_cp4d_cartridge.olm_utils_name }}.yml"
  when: 
  - (_current_cp4d_cartridge.state | default('installed')) == 'installed'
  - (_current_cp4d_cartridge.separate_install | default(False) | bool)