---
- name: Resume the Machine Config Operator
  include_tasks: resume-mco.yml
  when: 
  - _mco_exists
  - cloud_platform != 'aws'

- name: Apply the node settings if the Machine Config Operator does not exist
  include_tasks: non-mco-apply-node-settings.yml
  when: 
  - not _mco_exists
  - cloud_platform != 'aws'