---
- block:
  - set_fact:
      _configured_cartridge: "{{ _cartridges_to_install | json_query(query) | first | default({}) }}"
    vars:
      query: >-
        [?name=='{{ _current_cartridge_cr.name }}']

  - name: Check if cartridge {{ _current_cartridge_cr.name }} is currently installed
    shell: |
      oc get {{ _current_cartridge_cr.cr_cr }} {{ _current_cartridge_cr.cr_name }} --namespace {{ _p_current_cp4d_cluster.project }}
    failed_when: False
    register: _cartridge_installed

  - include_tasks: cp4d-remove-cr.yml
    when:
    - not (_configured_cartridge.Component_name | default('')) in _cartridge_dependencies
    - not (_configured_cartridge.component_alt_name | default('')) in _cartridge_dependencies
    - _cartridge_installed.rc == 0
    - _configured_cartridge == {} or ((_configured_cartridge.state | default('installed')) == 'removed' )