---
- set_fact:
    cp4d_admin_password_vault_key_name: "cp4d_admin_{{ current_cp4d_cluster.project| replace('-','_') }}_{{ current_cp4d_cluster.openshift_cluster_name| replace('-','_') }}"

- name: Get admin password {{ cp4d_admin_password_vault_key_name }} from the vault
  include_role: 
    name: vault-get-secret
  vars:
    secret_name: "{{ cp4d_admin_password_vault_key_name }}"
    secret_group: "{{ environment_name }}"
    _p_secret_variable: _cp4d_admin_password

- name: Get Route to Cloud Pak for Data
  shell: |
    oc --namespace {{ current_cp4d_cluster.project }} get route -l component=ibm-nginx \
      -o jsonpath="{.items[0].spec.host}"
  register: cp4d_url

- name: Make sure that directory {{ status_dir }}/cloud-paks exists
  file:
    path: "{{ status_dir }}/cloud-paks"
    state: directory

- name: Store Cloud Pak for Data URL into log file
  copy:
    content: "Cloud Pak for Data URL for cluster {{ current_cp4d_cluster.openshift_cluster_name }} and project {{ current_cp4d_cluster.project }}: \nhttps://{{ cp4d_url.stdout }}\n"
    dest: "{{ status_dir }}/cloud-paks/cp4d-{{ current_cp4d_cluster.openshift_cluster_name }}-{{ current_cp4d_cluster.project }}.url"

- name: Show Cloud Pak for Data URL and admin password
  debug:
    msg: 
    - "CP4D URL: https://{{ cp4d_url.stdout }}"
    - "CP4D admin password: {{ _cp4d_admin_password }}"
  vars:
    ansible_callback_diy_runner_on_ok_msg: "{{ ansible_callback_diy.result.output.msg }}\n"
