---
- name: Create downloads directory
  file:
    path: "{{ status_dir }}/downloads"
    state: directory

- name: Check if cloudctl was already downloaded
  stat:
    path: "{{ status_dir }}/downloads/cloudctl-linux-amd64.tar.gz"
  register: _cloudctl_download

- block:

  - name: Get current version number of clouctl
    uri:
      url: https://api.github.com/repos/IBM/cloud-pak-cli/releases/latest
      return_content: yes
      method: GET
      status_code: 200
    register: _cloudctl_version

  - name: Download cloudctl tool
    get_url:
      url: "https://github.com/IBM/cloud-pak-cli/releases/download/{{ _cloudctl_version.json.tag_name }}/cloudctl-linux-amd64.tar.gz"
      dest: "{{ status_dir }}/downloads/cloudctl-linux-amd64.tar.gz"
      owner: root
      mode: 0644
    register: _download_result
    until: _download_result is succeeded
    retries: 5
    delay: 30

  when: not _cloudctl_download.stat.exists

- name: Unpack cloudctl from {{ status_dir }}/downloads/cloudctl-linux-amd64.tar.gz
  unarchive:
    src: "{{ status_dir }}/downloads/cloudctl-linux-amd64.tar.gz"
    dest: "{{ status_dir }}/downloads"

- name: Rename to cloudctl
  shell: |
    mv -f {{ status_dir }}/downloads/cloudctl-linux-amd64 {{ status_dir }}/downloads/cloudctl

- name: Make sure cloudctl can be run within path
  copy:
    src: "{{ status_dir }}/downloads/cloudctl"
    dest: /usr/local/bin/cloudctl
    mode: preserve
    remote_src: True

- name: Get cloudctl version
  shell: |
    cloudctl version
  register: _cloudctl_version

- name: Show cloudctl version
  debug:
    var: _cloudctl_version.stdout