---
- name: Create temporary directory to hold current global pull secret content
  tempfile:
    state: directory
  register: pull_secret_dir

- name: Extract the global pull secret
  shell: |
    oc extract secret/pull-secret -n openshift-config --confirm --to={{ pull_secret_dir.path }}

- name: Add global pull secret to node fix secret
  shell: |
    oc set data -n kube-system secret/cloud-pak-node-fix-secrets \
      --from-file=newdockerconfigjson={{ pull_secret_dir.path }}/.dockerconfigjson