---
- include_role:
    name: cp4d-variables
    
- set_fact:
    _case_dir: "{{ status_dir }}/cp4d/case"

- name: Create directory {{ _case_dir }} for case files
  file:
    path: "{{ _case_dir }}"
    state: directory

- name: Show current Cloud Pak for Data cluster
  debug:
    var: _p_current_cp4d_cluster

- name: Get OpenShift cluster definition for Cloud Pak for Data cluter
  set_fact:
    _openshift_config: "{{ all_config.openshift | json_query(query) | first | default({}) }}"
  vars:
    query: >-
      [?name=='{{ _p_current_cp4d_cluster.openshift_cluster_name }}']

- name: Retrieve processor architecture for OpenShift cluster
  set_fact:
    _openshift_processor_arch: "{{ _openshift_config.infrastructure.processor_architecture | default('amd64') }}"

- include_tasks: download-case-olm-utils.yml