---
- block:
  - set_fact:
      _case_dir: "{{ status_dir }}/cp4d/case/{{ _p_current_cp4d_cluster.cp4d_version }}/{{ _current_cartridge.olm_utils_name }}"

  - name: Retrieve case file for {{ _current_cartridge.name }} in the {{ _case_dir }} directory
    find:
      paths: "{{ _case_dir }}"
      patterns: "^{{ _current_cartridge.search_string }}-[0-9]+[.][0-9]+[.][0-9]+.*[.]tgz"
      use_regex: yes
    register: _case_files

  - name: Show case file definitions that were found using the pattern
    debug:
      var: _case_files

  - set_fact:
      _case_file: "{{ _case_files.files | first | default({}) }}"

  - name: Show current case file
    debug:
      var: _case_file

  # Install catalog if case file for cartridge was found
  - block:
    - name: Compose cloudctl install-catalog command for case file {{ _case_file.path }}
      set_fact:
        _install_catalog_command: "{{ lookup('template','install-catalog-command.j2') }}"

    - name: Show install-catalog command that will be used
      debug:
        var: _install_catalog_command

    - name: Run cloudctl install-catalog for case file {{ _case_file.path }}
      shell: |
        {{ _install_catalog_command }}
    when: 
      - _case_file != {}
      
  when: 
    - not (_current_cartridge.cr_internal | default(False) | bool)