---
- name: Create catalog sources from case files in {{ status_dir }}/cp4d/case directory
  include_tasks: create-catalog-source-case-file.yml
  loop: "{{ _cartridges_to_install }}"
  loop_control:
    loop_var: _current_cartridge