---
- name: Create ImageContentSourcePolicy
  include_tasks: create-icsp.yml
  when: _mco_exists

- name: Apply ImageContentSourcePolicy settings if the Machine Config Operator does not exist
  include_tasks: non-mco-apply-icsp.yml
  when: not _mco_exists