---
- name: Check if aro-tenant-id secret is in the vault
  include_role:
    name: vault-get-secret
  vars:
    secret_name: "aro-tenant-id"
    secret_group: "{{ environment_name }}"

- name: Check that aro-tenant-id secret is present in the vault
  fail:
    msg: "Secret aro-tenant-id is mandatory and was not found in the vault"
  when: secret_value==""

- name: Check if aro-subscription-id secret is in the vault
  include_role:
    name: vault-get-secret
  vars:
    secret_name: "aro-subscription-id"
    secret_group: "{{ environment_name }}"

- name: Check that aro-subscription-id secret is present in the vault
  fail:
    msg: "Secret aro-subscription-id is mandatory and was not found in the vault"
  when: secret_value==""

- name: Check if aro-sp-id secret is in the vault
  include_role:
    name: vault-get-secret
  vars:
    secret_name: "aro-sp-id"
    secret_group: "{{ environment_name }}"

- name: Check that aro-sp-id secret is present in the vault
  fail:
    msg: "Secret aro-sp-id is mandatory and was not found in the vault"
  when: secret_value==""

- name: Check if aro-sp-secret secret is in the vault
  include_role:
    name: vault-get-secret
  vars:
    secret_name: "aro-sp-secret"
    secret_group: "{{ environment_name }}"

- name: Check that aro-sp-secret secret is present in the vault
  fail:
    msg: "Secret aro-sp-secret is mandatory and was not found in the vault"
  when: secret_value==""

- name: Check if aro-sp-object-id secret is in the vault
  include_role:
    name: vault-get-secret
  vars:
    secret_name: "aro-sp-object-id"
    secret_group: "{{ environment_name }}"

- name: Check that aro-sp-object-id secret is present in the vault
  fail:
    msg: "Secret aro-sp-object-id is mandatory and was not found in the vault"
  when: secret_value==""

- name: Check if aro-rp-object-id secret is in the vault
  include_role:
    name: vault-get-secret
  vars:
    secret_name: "aro-rp-object-id"
    secret_group: "{{ environment_name }}"

- name: Check that aro-rp-object-id secret is present in the vault
  fail:
    msg: "Secret aro-rp-object-id is mandatory and was not found in the vault"
  when: secret_value==""

- name: Check if ocp-pullsecret secret is in the vault
  include_role:
    name: vault-get-secret
  vars:
    secret_name: "ocp-pullsecret"
    secret_group: "{{ environment_name }}"

- name: Check that ocp-pullsecret secret is present in the vault
  fail:
    msg: "Secret ocp-pullsecret is mandatory and was not found in the vault"
  when: secret_value==""
