---

# NOTE: This task is not used anymore and it will be removed in one of the next versions
# See create-instance.yml instead.

# --------------------- FIND INSTANCE TYPE DEFINITION  --------------
 
- name: Get the details for Platform Navigator instance type
  set_fact:
    _pn_type_def: "{{ instance_types | json_query(query) | first | default({}) }}"
  vars:
    query: >-
      [?type=='platform-navigator']

- fail:
    msg: The Platform Navigator instance type details not found
  when: _pn_type_def=={}

# --------------------- DETERMINE SUBSCRIPTION NAME -----------------

# Top level operators are not used anymore

# - set_fact:
#     _subscription_name: "{{ _pn_type_def.package_name }}-{{_pn_instance_def.channel}}-{{_pn_type_def.source_catalog_online}}-openshift-marketplace"
#   when: _use_top_level_operator

- set_fact:
    _subscription_name: "{{ _pn_type_def.package_name }}"
# when: not _use_top_level_operator

- debug:
    msg: "Subscription name: {{ _subscription_name }}"


# --------------------- WAIT FOR SUBSCRIPTION -----------------------

- name: Wait for the Platform Navigator Operator subscription
  shell: |
    subscription_name="{{_subscription_name}}"
    csv=$(oc get subscription -n openshift-operators ${subscription_name} -o json | jq -r .status.currentCSV)
    if [[ "$csv" == "null" ]]; then
      echo "null"
    else
      oc get csv -n openshift-operators ${csv} -o json 2>/dev/null | jq -r .status.phase
    fi
  register: pn_phase
  retries: 100
  delay: 20
  until: pn_phase.stdout == "Succeeded"

# --------------------- CREATE INSTANCE -----------------------------

- name: Verify if platform navigator already exists
  shell: |
    oc get PlatformNavigator {{_pn_instance_def.name}} -n {{current_cp4i_cluster.project}} | grep -i '^{{_pn_instance_def.name}}' | wc -l
  register: pn_exists

- name: Prepare yaml file for creating instance
  template:
    src: cp4i-platform-navigator.j2
    dest: "{{ status_dir }}/cp4i/cp4i-platform-navigator.yml"
  when: pn_exists.stdout == "0"

- name: Create instance from {{ status_dir }}/cp4di/cp4i-platform-navigator.yml
  shell: |
    oc apply -f {{ status_dir }}/cp4i/cp4i-platform-navigator.yml
  when: pn_exists.stdout == "0"

- name: Wait for the Platform Navigator to become ready
  shell: |
    oc get PlatformNavigator -n {{current_cp4i_cluster.project}} {{_pn_instance_def.name}} -o json | jq -r '.status.conditions[] | select(.type=="Ready").status'
  register: pn_status
  retries: 300
  delay: 30
  until: pn_status.stdout == "True"
