---

- name: Download CASE file for {{ current_cp4i_instance.type }}
  block:

  - name: Find version specific instance type properties
    include_tasks: get-instance-properties.yml

  - name: Get the details for instance type {{ instance_properties.type }}
    set_fact:
      _instance_type_details: "{{ instance_types | json_query(query) | first | default({}) }}"
    vars:
      query: >-
        [?type=='{{ instance_properties.type }}']

  - fail:
      msg: The definition of instance type {{ instance_properties.type }} not found
    when: _instance_type_details=={}

  - name: Save case file {{ _instance_type_details.package_name }}-{{ instance_properties.case_version }}
    shell: |
      cloudctl case save \
        --repo {{ case_github_url }} \
        --case {{ _instance_type_details.package_name }} \
        --version {{ instance_properties.case_version }} \
        --outputdir {{ _case_dir }} 

  when: (current_cp4i_instance.state | default('installed')) == 'installed'


