---

# NOTE: This task is not used anymore and it will be removed in one of the next versions
# See create-instance.yml instead.


- name: Find Platform Navigator instance definition
  set_fact:
    _pn_instance_def: "{{ current_cp4i_cluster.instances | json_query(query) | first | default({}) }}"
  vars:
    query: >-
      [?type=='platform-navigator']

- set_fact:
    _pn_defined: True

- set_fact:
    _pn_defined: False
  when: (_pn_instance_def.name | default("")) == ""

- name: Create Platfrom Navigator instance
  include_tasks: create-platform-navigator-instance.yml
  when: _pn_defined

