---

- name: Prepare yaml file for creating operator group
  template:
    src: operator-group.j2
    dest: "{{ status_dir }}/cp4i/operator-group.yml"

- name: "Create operator group using {{ status_dir }}/cp4i/operator-group.yml"
  shell: |
    oc apply -f {{ status_dir }}/cp4i/operator-group.yml
