---
- name: Download and install Azure command line tool (for destoy action)
  include_role:
    name: azure-download-az
  when: cpd_action == "destroy"

- name: Download and install Terraform (for apply action)
  include_role:
    name: terraform-download
  when: cpd_action == "apply"
