---
- name: Get secret Validate mandatory variables are defined
  assert:
    that:
      - ibm_cloud_secret_name is defined
      - ibmcloud_vault_address is defined
      - ibm_vault_token_content is defined

- name: Fail if a secret field was specified for a vault other than Hashicorp
  fail:
    msg: "Secret name {{ ibm_cloud_secret_name }} can only have a secret field specification for Hashicorp Vault"
  when: ibm_cloud_secret_name is search(",")

- name: Get the secret id if the secret exists
  include_role:
    name: vault-has-secret

- name: Get secret value
  block:
    - name: Get Secret {{ secret_name }} from group {{ secret_group }}
      uri:
        url: "{{ ibmcloud_vault_address }}/v1/ibmcloud/arbitrary/secrets/groups/{{ ibm_cloud_secret_group_id }}/{{ secret_id }}"
        headers:
          X-Vault-Token: "{{ ibm_vault_token_content.auth.client_token }}"
          Accept: "application/json"
        status_code: 200
      register: response_getSecret

    - set_fact:
        secret_value: "{{ response_getSecret.json.data.secret_data.payload | b64decode }}"
  when: "has_secret == true"

- set_fact:
    secret_value: ""
  when: "has_secret == false"

- name: Write secret to file {{ secret_file }} if one was specified
  shell: echo "{{ secret_value }}" > "{{ secret_file }}"
  when: 
  - secret_file | default("") != ''  


